#!/bin/bash

# ensure running as root
if [ "$(id -u)" != "0" ]
then
	>&2 echo "you must run as root"
	exit 1
fi

ssid=$1
if [ -z "$ssid" ]
then
	ssid=$(iwgetid -r)
	if [ -z "$ssid" ]
	then
		>&2 echo "No wifi network connected or specified"
		exit 1
	fi
fi
if [ ! -f "/etc/NetworkManager/system-connections/$ssid" ]
then
	>&2 echo "No wifi password found for SSID $ssid"
	exit 1
fi
pass=$(grep psk= "/etc/NetworkManager/system-connections/$ssid" | cut -c 5-)

echo "SSID: $ssid"
echo "Password: $pass"
