#!/bin/bash

# ensure running as root
if [ "$(id -u)" != "0" ]
then
	>&2 echo "you must run as root"
	exit 1
fi

ssid=$1
if [ -z "$ssid" ]
then
	ssid=$(iwgetid -r)
	if [ -z "$ssid" ]
	then
		>&2 echo "No wifi network connected or specified"
		exit 1
	fi
fi
ssid_path="/etc/NetworkManager/system-connections/$ssid"
if [ ! -f "$ssid_path" ]
then
	ssid_path="/etc/NetworkManager/system-connections/Auto $ssid"
fi
if [ ! -f "$ssid_path" ]
then
	>&2 echo "No wifi password found for SSID $ssid"
	exit 1
fi
pass=$(grep psk= "$ssid_path" | cut -c 5-)

echo "SSID: $ssid"
echo "Password: $pass"
